apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: webgame
  namespace: lurus-webgame
  labels:
    app: webgame
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`webgame.lurus.cn`)
      kind: Rule
      services:
        - name: webgame
          port: 80
  tls:
    secretName: lurus-cn-wildcard-tls
